### ISSUE TITLE
Windows logfx.bat doesn't work if directory has spaces

### ISSUE THREAD

**Issue by marinier** [renatoathaydes/LogFX#29]
On my Windows 10 machine, the path to where logfx.bat is located has spaces and a dash in it. This causes logfx.bat to fail to start with this error :

```
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The fix is to to put quotes around the `VM_OPTIONS`, like this:

```
set VM_OPTIONS="-splash:%DIR%logfx-logo.png -Xms32m -XX:+UseSerialGC"
```

With that change, it starts up.

**Comment by renatoathaydes** [comment]
Silly mistake :( I don't use Windows often so never noticed that.
Will fix it soon. Thanks.
