### ISSUE TITLE
Add a color chooser

### ISSUE THREAD

**Issue by tchule** [renatoathaydes/LogFX#8]
Hello, nice tool

When in the "Highlight Options" menu I instinctively clicked on a colored square expecting a color chooser to pop up. Would be a nice addition.

Best Regards,

**Comment by renatoathaydes** [comment]
@tchule I agree, but the JavaFX native color picker was ugly and didn't work as I wanted... but I think I could use a library that provides a nicer one, so I will have a look at that...

If you know of any good ones, let me know.

**Comment by renatoathaydes** [comment]
I think I will add JFoenix components to LogFX.
The color picker is pretty awesome: https://camo.githubusercontent.com/9e2a9ff9c2c15ff636f09124f0405419060765ae/687474703a2f2f6a666f656e69782e636f6d2f6769662f636f6c6f727069636b65722d626574612e676966

@tchule

**Comment by tchule** [comment]
Looks nice ^^

**Comment by renatoathaydes** [comment]
I decided to use the default JavaFX color-chooser.

The JFoenix project is a over 2MB jar! Considering LogFX currently is around 300kb, and it's a goal to remain lean, I don't think it's worth it using that.

But I checked the latest JavaFX color-chooser, and it's not too bad at all, looks quite nice.

Will try to release it soon.

**Comment by renatoathaydes** [comment]
Released version 0.8.0 with a color picker!
Please let me know if you like it :)

And the jar is still around 300kb.

**Comment by tchule** [comment]
Perfect, nice and clean. Thx.
